# Site settings
title: Nayeem Ahamed
description: Nayeem Ahamed
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nayeem Ahamed
user_description: The movie Three Idiots piqued my interest when I was a student of 9th grade. This went on for long enough for me to complete an engineering degree. I’m an Industrial & Production Engineer from Ahsanullah University of Science and Technology (AUST). Here, I learnt how engineering and business can be molded into a single cavity. Through the PTAK & business competition, I began to understand about supply chain. Furthermore, I was always fascinated by how an organization worked from start until the end. It eventually lead me down several rabbit holes, and I soon discovered an entirely different universe in this sector. So now I'm doing my best to achieve the excellence and learn the nuts and bolts; there is to know about it.
user_title: Industrial and Production Engineer
email: nayeemahamedador@gmail.com
medium_username: https://medium.com/@nayeemahamedador
linkedin_username:  https://www.linkedin.com/in/nayeem-ahamed-csca%E2%84%A2-a96105147?fbclid=IwAR1cxdXQKR_KI8vDT2K_ipRSxXvWBgRpWdhlU8prtfwA3ioGulij7ccqmcE


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
